"""empty message

Revision ID: 33087eb7731e
Revises: 7e6eedc7b3df
Create Date: 2020-09-28 23:54:03.944961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33087eb7731e'
down_revision = '7e6eedc7b3df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('show_date_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'show_date_time')
    # ### end Alembic commands ###
